### ISSUE TITLE
Exception: Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None

### ISSUE THREAD

**Issue by able2608** [ali-vilab/ACE#1]
First of all, thanks for the work on this project and open-sourcing the code and model to the community.
I am currently trying to setup the gradio demo on a Windows machine with NVIDIA GPU and CUDA enabled. However, it seems that the current demo code is unable to download the model from Modelscope automatically. Specifically, when trying to initialize `scepter.modules.model.network.autoencoder.ae_kl.AutoencoderKL`, it returns the error `Failed to init class <class 'scepter.modules.model.network.autoencoder.ae_kl.AutoencoderKL'>, with Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None`. Some key specs and the environment this repo is in is listed below for reference (more information can be posted if needed):

- Platform: Windows 11 Home 23H2
- CUDA (in the environment): 12.1
- Python Version: 3.12.0
- The rest of the libraries in the environment are as listed in the provided `requirements.txt`, except that I installed pytorch with conda (with matching version) and added `xformers==0.0.27.post2` as your codebase warns about it not being installed.

I am not pretty sure if it is because of the code base's problem or ModelScope's issue, but I am pretty sure that I am able to open the ModelScope website without a hitch. Hope that someone in your team can help figure that out.

The full log is attached below. Note that I did have to modify 2 things in order to make it work, perhaps they can also be fixed alongside this issue:
- ACE\chatbot\run_gradio.py Line 61
`model_name = '.'.join(i.split('/')[-1].split('.')[:-1])` ->  `model_name = '.'.join(os.path.basename(i).split('.')[:-1])`, else it is unable to find the model specs (Assertion on Line 66 will fail due to `model_name` being `models\\ace_0.6b_512` , I assume that Line 61 is trying to extract the file name of the yaml files in the `chatbot/configs/models` folder)
- scepter\modules\model\backbone\unet\unet_utils.py Line 6
`from importlib import find_loader` -> `from importlib.util import find_spec as find_loader`, else it cannot find `find_loader` and throws `ModuleNotFoundError` (perhaps it is because `find_loader` was deprecated and removed for newer versions of importlib, per the documentation stated )
```
(D:\ACE\venv) D:\ACE>python chatbot/run_gradio.py --cfg chatbot/config/chatbot_ui.yaml
D:\ACE\chatbot\run_gradio.py:532: SyntaxWarning: invalid escape sequence '\s'
  prompt = re.sub(f'@{img_id}\s+', '', message)
D:\ACE\venv\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
D:\ACE\venv\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\ACE\venv\Lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
    ^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'triton'
D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:178: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:192: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:228: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:270: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\venv\Lib\site-packages\scepter\modules\solver\base_solver.py:189: UserWarning: No module named 'pytorch_lightning'
  warnings.warn(f'{e}')
D:\ACE\modules\model\backbone\pos_embed.py:37: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\modules\model\backbone\pos_embed.py:74: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ddim already registered by <class 'scepter.modules.model.diffusion.samplers.DDIMSampler'>, will be replaced by <class 'scepter_ext.modules.model.diffusion.samplers.DDIMSampler'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class LinearScheduler already registered by <class 'scepter.modules.model.diffusion.schedules.LinearScheduler'>, will be replaced by <class 'scepter_ext.modules.model.diffusion.schedules.LinearScheduler'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACEDemoDataset already registered by <class 'scepter_ext.modules.data.dataset.dataset.ACEDemoDataset'>, will be replaced by <class 'modules.data.dataset.dataset.ACEDemoDataset'>
  warnings.warn(
D:\ACE\modules\model\backbone\pos_embed.py:37: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\modules\model\backbone\pos_embed.py:74: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class DiTACE already registered by <class 'scepter_ext.modules.model.backbone.ace.DiTACE'>, will be replaced by <class 'modules.model.backbone.ace.DiTACE'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACETextEmbedder already registered by <class 'scepter_ext.modules.model.embedder.embedder.ACETextEmbedder'>, will be replaced by <class 'modules.model.embedder.embedder.ACETextEmbedder'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACEDiffusion already registered by <class 'scepter_ext.modules.model.diffusion.diffusions.ACEDiffusion'>, will be replaced by <class 'modules.model.diffusion.diffusions.ACEDiffusion'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ddim already registered by <class 'scepter_ext.modules.model.diffusion.samplers.DDIMSampler'>, will be replaced by <class 'modules.model.diffusion.samplers.DDIMSampler'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class LinearScheduler already registered by <class 'scepter_ext.modules.model.diffusion.schedules.LinearScheduler'>, will be replaced by <class 'modules.model.diffusion.schedules.LinearScheduler'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class LdmACE already registered by <class 'scepter_ext.modules.model.network.ldm_ace.LdmACE'>, will be replaced by <class 'modules.model.network.ldm_ace.LdmACE'>
  warnings.warn(
D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACESolverV1 already registered by <class 'scepter_ext.modules.solver.ace_solver.ACESolverV1'>, will be replaced by <class 'modules.solver.ace_solver.ACESolverV1'>
  warnings.warn(
[Info]: Loading config from [chatbot/config/chatbot_ui.yaml] as yaml file.
Downloading Examples ...
Finish. Start building UI ...
Models:  {'ace_0.6b_512': 'chatbot/config/models\\ace_0.6b_512.yaml'}
[Info]: Loading config from [chatbot/config/models\ace_0.6b_512.yaml] as yaml file.
scepter [INFO] 2024-11-10 21:55:30,346 [File: diffusion_inference.py Function: dynamic_load at line 275]  Loading first_stage_model model
scepter [INFO] 2024-11-10 21:55:30,347 [File: ae_module.py Function: construct_model at line 76]  AE Module XFORMERS_IS_AVAILBLE : True
2024-11-10 21:55:31,152 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:31,541 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:31,917 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:32,313 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:32,704 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:33,119 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:33,502 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:33,906 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:34,273 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
2024-11-10 21:55:34,649 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
Traceback (most recent call last):
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py", line 78, in build_from_config
    return req_type_entry(cfg, logger=logger, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\model\network\autoencoder\ae_kl.py", line 102, in __init__
    self.init_network()
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\model\network\autoencoder\ae_kl.py", line 120, in init_network
    with FS.get_from(self.pretrained_model,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\file_system.py", line 248, in get_from
    raise ReadException(
scepter.modules.utils.file_system.ReadException: Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ACE\chatbot\run_gradio.py", line 1227, in <module>
    run_gr(cfg)
  File "D:\ACE\chatbot\run_gradio.py", line 1209, in run_gr
    chatbot = ChatBotUI(cfg)
              ^^^^^^^^^^^^^^
  File "D:\ACE\chatbot\run_gradio.py", line 70, in __init__
    self.pipe.init_from_cfg(model_cfg)
  File "D:\ACE\chatbot\infer.py", line 141, in init_from_cfg
    self.dynamic_load(self.first_stage_model, 'first_stage_model')
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\inference\diffusion_inference.py", line 293, in dynamic_load
    module = self.load(module)
             ^^^^^^^^^^^^^^^^^
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\inference\diffusion_inference.py", line 233, in load
    model = MODELS.build(module['cfg'], logger=self.logger).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py", line 135, in build
    return self.build_func(cfg,
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\model\registry.py", line 23, in build_model
    model = build_from_config(cfg, registry, logger=logger, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py", line 80, in build_from_config
    raise Exception(f'Failed to init class {req_type_entry}, with {e}')
Exception: Failed to init class <class 'scepter.modules.model.network.autoencoder.ae_kl.AutoencoderKL'>, with Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None
```

**Comment by able2608** [comment]
As a side note, since the model is already on huggingface, perhaps it would be nice to also be able to download them from there?

**Comment by able2608** [comment]
> First of all, thanks for the work on this project and open-sourcing the code and model to the community. I am currently trying to setup the gradio demo on a Windows machine with NVIDIA GPU and CUDA enabled. However, it seems that the current demo code is unable to download the model from Modelscope automatically. Specifically, when trying to initialize `scepter.modules.model.network.autoencoder.ae_kl.AutoencoderKL`, it returns the error `Failed to init class <class 'scepter.modules.model.network.autoencoder.ae_kl.AutoencoderKL'>, with Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None`. Some key specs and the environment this repo is in is listed below for reference (more information can be posted if needed):
> 
>     * Platform: Windows 11 Home 23H2
> 
>     * CUDA (in the environment): 12.1
> 
>     * Python Version: 3.12.0
> 
>     * The rest of the libraries in the environment are as listed in the provided `requirements.txt`, except that I installed pytorch with conda (with matching version) and added `xformers==0.0.27.post2` as your codebase warns about it not being installed.
> 
> 
> I am not pretty sure if it is because of the code base's problem or ModelScope's issue, but I am pretty sure that I am able to open the ModelScope website without a hitch. Hope that someone in your team can help figure that out.
> 
> The full log is attached below. Note that I did have to modify 2 things in order to make it work, perhaps they can also be fixed alongside this issue:
> 
>     * ACE\chatbot\run_gradio.py Line 61
>       `model_name = '.'.join(i.split('/')[-1].split('.')[:-1])` ->  `model_name = '.'.join(os.path.basename(i).split('.')[:-1])`, else it is unable to find the model specs (Assertion on Line 66 will fail due to `model_name` being `models\\ace_0.6b_512` , I assume that Line 61 is trying to extract the file name of the yaml files in the `chatbot/configs/models` folder)
> 
>     * scepter\modules\model\backbone\unet\unet_utils.py Line 6
>       `from importlib import find_loader` -> `from importlib.util import find_spec as find_loader`, else it cannot find `find_loader` and throws `ModuleNotFoundError` (perhaps it is because `find_loader` was deprecated and removed for newer versions of importlib, per the documentation stated )
> 
> 
> ```
> (D:\ACE\venv) D:\ACE>python chatbot/run_gradio.py --cfg chatbot/config/chatbot_ui.yaml
> D:\ACE\chatbot\run_gradio.py:532: SyntaxWarning: invalid escape sequence '\s'
>   prompt = re.sub(f'@{img_id}\s+', '', message)
> D:\ACE\venv\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
>   @torch.library.impl_abstract("xformers_flash::flash_fwd")
> D:\ACE\venv\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
>   @torch.library.impl_abstract("xformers_flash::flash_bwd")
> A matching Triton is not available, some optimizations will not be enabled
> Traceback (most recent call last):
>   File "D:\ACE\venv\Lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
>     import triton  # noqa
>     ^^^^^^^^^^^^^
> ModuleNotFoundError: No module named 'triton'
> D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:178: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:192: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:228: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\venv\Lib\site-packages\scepter\modules\model\backbone\transformer\pos_embed.py:270: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\venv\Lib\site-packages\scepter\modules\solver\base_solver.py:189: UserWarning: No module named 'pytorch_lightning'
>   warnings.warn(f'{e}')
> D:\ACE\modules\model\backbone\pos_embed.py:37: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\modules\model\backbone\pos_embed.py:74: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ddim already registered by <class 'scepter.modules.model.diffusion.samplers.DDIMSampler'>, will be replaced by <class 'scepter_ext.modules.model.diffusion.samplers.DDIMSampler'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class LinearScheduler already registered by <class 'scepter.modules.model.diffusion.schedules.LinearScheduler'>, will be replaced by <class 'scepter_ext.modules.model.diffusion.schedules.LinearScheduler'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACEDemoDataset already registered by <class 'scepter_ext.modules.data.dataset.dataset.ACEDemoDataset'>, will be replaced by <class 'modules.data.dataset.dataset.ACEDemoDataset'>
>   warnings.warn(
> D:\ACE\modules\model\backbone\pos_embed.py:37: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\modules\model\backbone\pos_embed.py:74: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
>   @amp.autocast(enabled=False)
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class DiTACE already registered by <class 'scepter_ext.modules.model.backbone.ace.DiTACE'>, will be replaced by <class 'modules.model.backbone.ace.DiTACE'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACETextEmbedder already registered by <class 'scepter_ext.modules.model.embedder.embedder.ACETextEmbedder'>, will be replaced by <class 'modules.model.embedder.embedder.ACETextEmbedder'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACEDiffusion already registered by <class 'scepter_ext.modules.model.diffusion.diffusions.ACEDiffusion'>, will be replaced by <class 'modules.model.diffusion.diffusions.ACEDiffusion'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ddim already registered by <class 'scepter_ext.modules.model.diffusion.samplers.DDIMSampler'>, will be replaced by <class 'modules.model.diffusion.samplers.DDIMSampler'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class LinearScheduler already registered by <class 'scepter_ext.modules.model.diffusion.schedules.LinearScheduler'>, will be replaced by <class 'modules.model.diffusion.schedules.LinearScheduler'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class LdmACE already registered by <class 'scepter_ext.modules.model.network.ldm_ace.LdmACE'>, will be replaced by <class 'modules.model.network.ldm_ace.LdmACE'>
>   warnings.warn(
> D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py:151: UserWarning: Class ACESolverV1 already registered by <class 'scepter_ext.modules.solver.ace_solver.ACESolverV1'>, will be replaced by <class 'modules.solver.ace_solver.ACESolverV1'>
>   warnings.warn(
> [Info]: Loading config from [chatbot/config/chatbot_ui.yaml] as yaml file.
> Downloading Examples ...
> Finish. Start building UI ...
> Models:  {'ace_0.6b_512': 'chatbot/config/models\\ace_0.6b_512.yaml'}
> [Info]: Loading config from [chatbot/config/models\ace_0.6b_512.yaml] as yaml file.
> scepter [INFO] 2024-11-10 21:55:30,346 [File: diffusion_inference.py Function: dynamic_load at line 275]  Loading first_stage_model model
> scepter [INFO] 2024-11-10 21:55:30,347 [File: ae_module.py Function: construct_model at line 76]  AE Module XFORMERS_IS_AVAILBLE : True
> 2024-11-10 21:55:31,152 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:31,541 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:31,917 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:32,313 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:32,704 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:33,119 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:33,502 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:33,906 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:34,273 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> 2024-11-10 21:55:34,649 - modelscope - ERROR - The request model: iic\ACE-0.6B-512px does not exist!
> Traceback (most recent call last):
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py", line 78, in build_from_config
>     return req_type_entry(cfg, logger=logger, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\model\network\autoencoder\ae_kl.py", line 102, in __init__
>     self.init_network()
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\model\network\autoencoder\ae_kl.py", line 120, in init_network
>     with FS.get_from(self.pretrained_model,
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\file_system.py", line 248, in get_from
>     raise ReadException(
> scepter.modules.utils.file_system.ReadException: Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\ACE\chatbot\run_gradio.py", line 1227, in <module>
>     run_gr(cfg)
>   File "D:\ACE\chatbot\run_gradio.py", line 1209, in run_gr
>     chatbot = ChatBotUI(cfg)
>               ^^^^^^^^^^^^^^
>   File "D:\ACE\chatbot\run_gradio.py", line 70, in __init__
>     self.pipe.init_from_cfg(model_cfg)
>   File "D:\ACE\chatbot\infer.py", line 141, in init_from_cfg
>     self.dynamic_load(self.first_stage_model, 'first_stage_model')
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\inference\diffusion_inference.py", line 293, in dynamic_load
>     module = self.load(module)
>              ^^^^^^^^^^^^^^^^^
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\inference\diffusion_inference.py", line 233, in load
>     model = MODELS.build(module['cfg'], logger=self.logger).eval()
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py", line 135, in build
>     return self.build_func(cfg,
>            ^^^^^^^^^^^^^^^^^^^^
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\model\registry.py", line 23, in build_model
>     model = build_from_config(cfg, registry, logger=logger, *args, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ACE\venv\Lib\site-packages\scepter\modules\utils\registry.py", line 80, in build_from_config
>     raise Exception(f'Failed to init class {req_type_entry}, with {e}')
> Exception: Failed to init class <class 'scepter.modules.model.network.autoencoder.ae_kl.AutoencoderKL'>, with Failed to fetch ms://iic/ACE-0.6B-512px@models/vae/vae.bin to None
> ```

Update: After switching download source to huggingface (using method described in the README file), the same error still occures. The problem probably does not originate from ModelScope.

**Comment by jiangzeyinzi** [comment]
The ACE is currently being developed and deployed primarily in a Linux environment. We will analyze the issues related to Windows compatibility and address them as soon as possible.

**Comment by LouieStark** [comment]
Hi @able2608 , a straightforward solution to this problem is to download the model from ModelScope or Hugging Face to your local machine. After downloading, simply update the value of EDIT_MODEL in chatbot/config/chatbot_ui.yaml to point to your local model path. The system will automatically determine whether a download is necessary.

**Comment by able2608** [comment]
Downloading the model manually definitely solved the issue. Thanks a lot! However, I do not seem to know how to edit EDIT_MODEL in the chatbot_ui.yaml to point to the local directory, thus I resorted to change the PRETRAINED_MODEL path in the model configuration file, and that got the thing working.
