### ISSUE TITLE
Training leads to image collapse

### ISSUE THREAD

**Issue by wangsh0111** [ali-vilab/ACE#6]
Hello~Thank you for your amazing work. I obtained good editing results using your script, but when I tried to train using your training demo data and script, the generated image quality was poor. Can you please take a look at what could be causing this?
![image](https://github.com/user-attachments/assets/19ed8ee0-061f-4962-a8eb-8ca46cc1c25c)

**Comment by maochaojie** [comment]
The training examples we provide are just a demo. To train a model with similar performance, you need to prepare the relevant data yourself. Training the ACE model requires a large scale of training data and a considerable training duration.

**Comment by wangsh0111** [comment]
> However, if you fine-tune the open-source model based on ACE using a small amount of your own pair data (through LoRA or fully fine-tuning), you can quickly integrate some new capabilities into the ACE model.

Thank you for your reply. I can use the training code provided by scepter to obtain the fine-tuning results I want through Lora. But I have recently encountered two new problems: 1. I obtained worse editing results using the 1024 model; 2. How to construct data to achieve high fidelity when editing.

**Comment by JasonHuangChina** [comment]
> Thank you for your reply. I can use the training code provided by scepter to obtain the fine-tuning results I want through Lora. But I have recently encountered two new problems: 1. I obtained worse editing results using the 1024 model; 2. How to construct data to achieve high fidelity when editing. Could you tell me how to solve these problems?

Hi, may I ask you a question? Where can I find the code for fine-tuning?
